apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: study-app
namePrefix: dev-
images:
  - name: docker pull ghcr.io/vinaysudani/study-app-api
    newTag: backend-v0.2.0
  - name: docker pull ghcr.io/vinaysudani/study-app-web
    newTag: frontend-v0.1.0
